Unauthorized: /cms-api/v1/posts/most_viewed/
Unauthorized: /cms-api/v1/posts/most_viewed/
Unauthorized: /cms-api/v1/posts/most_viewed/
Unauthorized: /cms-api/v1/posts/most_viewed/
Bad Request: /auth/token/logout/
Unauthorized: /cms-api/v1/posts/most_viewed/
Unauthorized: /cms-api/v1/posts/most_viewed/
Unauthorized: /cms-api/v1/posts/most_viewed/
Unauthorized: /cms-api/v1/posts/most_viewed/
Bad Request: /auth/token/logout/
Not Found: /schema/redoc/
Not Found: /favicon.ico
C:\Users\admin\Desktop\realtech-blogx\backend\cms\realtech_blogx\settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\models.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\models.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\models.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\models.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\serializers.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\serializers.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Bad Request: /auth/token/logout/
Not Found: /cms-api/v1/posts/search/
Not Found: /cms-api/v1/posts/search/
Not Found: /cms-api/v1/posts/search/
Not Found: /cms-api/v1/posts/search/
Not Found: /cms-api/v1/posts/search/
Not Found: /cms-api/v1/posts/search/
Not Found: /cms-api/v1/posts/search/
Not Found: /cms-api/v1/posts/search/
Not Found: /cms-api/v1/posts/search/
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Bad Request: /auth/token/logout/
Error retrieving user data: name 'profile_picture' is not defined
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /auth/token/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in default
    return tuple(item for item in obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in <genexpr>
    return tuple(item for item in obj)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 78, in __iter__
    for chunk in self.chunks():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 55, in chunks
    self.seek(0)
    ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\utils.py", line 45, in <lambda>
    seek = property(lambda self: self.file.seek)
                                 ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 49, in _get_file
    self._require_file()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 44, in _require_file
    raise ValueError(
ValueError: The 'profile_picture' attribute has no file associated with it.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Bad Request: /auth/token/logout/
Internal Server Error: /auth/token/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in default
    return tuple(item for item in obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in <genexpr>
    return tuple(item for item in obj)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 78, in __iter__
    for chunk in self.chunks():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 55, in chunks
    self.seek(0)
    ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\utils.py", line 45, in <lambda>
    seek = property(lambda self: self.file.seek)
                                 ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 49, in _get_file
    self._require_file()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 44, in _require_file
    raise ValueError(
ValueError: The 'profile_picture' attribute has no file associated with it.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Bad Request: /auth/token/logout/
Internal Server Error: /auth/token/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in default
    return tuple(item for item in obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in <genexpr>
    return tuple(item for item in obj)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 78, in __iter__
    for chunk in self.chunks():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 55, in chunks
    self.seek(0)
    ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\utils.py", line 45, in <lambda>
    seek = property(lambda self: self.file.seek)
                                 ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 49, in _get_file
    self._require_file()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 44, in _require_file
    raise ValueError(
ValueError: The 'profile_picture' attribute has no file associated with it.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Bad Request: /auth/token/logout/
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Bad Request: /auth/token/logout/
Internal Server Error: /auth/token/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in default
    return tuple(item for item in obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in <genexpr>
    return tuple(item for item in obj)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 78, in __iter__
    for chunk in self.chunks():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 55, in chunks
    self.seek(0)
    ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\utils.py", line 45, in <lambda>
    seek = property(lambda self: self.file.seek)
                                 ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 49, in _get_file
    self._require_file()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 44, in _require_file
    raise ValueError(
ValueError: The 'profile_picture' attribute has no file associated with it.
Bad Request: /auth/token/logout/
Unauthorized: /auth/token/
Internal Server Error: /auth/token/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in default
    return tuple(item for item in obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in <genexpr>
    return tuple(item for item in obj)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 78, in __iter__
    for chunk in self.chunks():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 55, in chunks
    self.seek(0)
    ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\utils.py", line 45, in <lambda>
    seek = property(lambda self: self.file.seek)
                                 ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 49, in _get_file
    self._require_file()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 44, in _require_file
    raise ValueError(
ValueError: The 'profile_picture' attribute has no file associated with it.
Watching for file changes with StatReloader
Unauthorized: /cms-api/v1/posts/most_viewed/
Unauthorized: /cms-api/v1/posts/most_viewed/
Bad Request: /auth/token/logout/
Unauthorized: /cms-api/v1/posts/most_viewed/
Unauthorized: /cms-api/v1/posts/most_viewed/
Unauthorized: /cms-api/v1/posts/most_viewed/
Unauthorized: /cms-api/v1/posts/most_viewed/
Unauthorized: /cms-api/v1/posts/most_viewed/
Unauthorized: /cms-api/v1/posts/most_viewed/
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /auth/token/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in default
    return tuple(item for item in obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in <genexpr>
    return tuple(item for item in obj)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 78, in __iter__
    for chunk in self.chunks():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 55, in chunks
    self.seek(0)
    ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\utils.py", line 45, in <lambda>
    seek = property(lambda self: self.file.seek)
                                 ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 49, in _get_file
    self._require_file()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 44, in _require_file
    raise ValueError(
ValueError: The 'profile_picture' attribute has no file associated with it.
Bad Request: /auth/token/logout/
Internal Server Error: /auth/token/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in default
    return tuple(item for item in obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in <genexpr>
    return tuple(item for item in obj)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 78, in __iter__
    for chunk in self.chunks():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 55, in chunks
    self.seek(0)
    ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\utils.py", line 45, in <lambda>
    seek = property(lambda self: self.file.seek)
                                 ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 49, in _get_file
    self._require_file()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 44, in _require_file
    raise ValueError(
ValueError: The 'profile_picture' attribute has no file associated with it.
Bad Request: /auth/token/logout/
Internal Server Error: /auth/token/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in default
    return tuple(item for item in obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in <genexpr>
    return tuple(item for item in obj)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 78, in __iter__
    for chunk in self.chunks():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 55, in chunks
    self.seek(0)
    ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\utils.py", line 45, in <lambda>
    seek = property(lambda self: self.file.seek)
                                 ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 49, in _get_file
    self._require_file()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 44, in _require_file
    raise ValueError(
ValueError: The 'profile_picture' attribute has no file associated with it.
Watching for file changes with StatReloader
Bad Request: /auth/token/logout/
Internal Server Error: /auth/token/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in default
    return tuple(item for item in obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in <genexpr>
    return tuple(item for item in obj)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 78, in __iter__
    for chunk in self.chunks():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 55, in chunks
    self.seek(0)
    ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\utils.py", line 45, in <lambda>
    seek = property(lambda self: self.file.seek)
                                 ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 49, in _get_file
    self._require_file()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 44, in _require_file
    raise ValueError(
ValueError: The 'profile_picture' attribute has no file associated with it.
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\serializers.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /auth/token/logout/
Watching for file changes with StatReloader
Internal Server Error: /cms-api/v1/posts/most_viewed/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\client\default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 416, in initial
    self.check_throttles(request)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 359, in check_throttles
    if not throttle.allow_request(request, self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\throttling.py", line 123, in allow_request
    self.history = self.cache.get(self.key, [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\cache.py", line 92, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\cache.py", line 36, in _decorator
    raise e.__cause__
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\client\default.py", line 258, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\redis\commands\core.py", line 1821, in get
    return self.execute_command("GET", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\redis\client.py", line 545, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\redis\connection.py", line 1074, in get_connection
    connection.connect()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\redis\connection.py", line 283, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.
Internal Server Error: /cms-api/v1/categories/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\client\default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 416, in initial
    self.check_throttles(request)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 359, in check_throttles
    if not throttle.allow_request(request, self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\throttling.py", line 123, in allow_request
    self.history = self.cache.get(self.key, [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\cache.py", line 92, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\cache.py", line 36, in _decorator
    raise e.__cause__
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\client\default.py", line 258, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\redis\commands\core.py", line 1821, in get
    return self.execute_command("GET", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\redis\client.py", line 545, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\redis\connection.py", line 1074, in get_connection
    connection.connect()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\redis\connection.py", line 283, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.
Internal Server Error: /cms-api/v1/posts/most_viewed/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\client\default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 416, in initial
    self.check_throttles(request)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 359, in check_throttles
    if not throttle.allow_request(request, self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\throttling.py", line 123, in allow_request
    self.history = self.cache.get(self.key, [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\cache.py", line 92, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\cache.py", line 36, in _decorator
    raise e.__cause__
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\client\default.py", line 258, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\redis\commands\core.py", line 1821, in get
    return self.execute_command("GET", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\redis\client.py", line 545, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\redis\connection.py", line 1074, in get_connection
    connection.connect()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\redis\connection.py", line 283, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.
Internal Server Error: /cms-api/v1/categories/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\client\default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 416, in initial
    self.check_throttles(request)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\views.py", line 359, in check_throttles
    if not throttle.allow_request(request, self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\throttling.py", line 123, in allow_request
    self.history = self.cache.get(self.key, [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\cache.py", line 92, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\cache.py", line 36, in _decorator
    raise e.__cause__
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_redis\client\default.py", line 258, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\redis\commands\core.py", line 1821, in get
    return self.execute_command("GET", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\redis\client.py", line 545, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\redis\connection.py", line 1074, in get_connection
    connection.connect()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\redis\connection.py", line 283, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.
Internal Server Error: /auth/token/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in default
    return tuple(item for item in obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in <genexpr>
    return tuple(item for item in obj)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 78, in __iter__
    for chunk in self.chunks():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 55, in chunks
    self.seek(0)
    ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\utils.py", line 45, in <lambda>
    seek = property(lambda self: self.file.seek)
                                 ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 49, in _get_file
    self._require_file()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 44, in _require_file
    raise ValueError(
ValueError: The 'profile_picture' attribute has no file associated with it.
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Tag slug is required
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
Bad Request: /cms-api/v1/posts/posts_by_category/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Tag slug is required
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
Bad Request: /cms-api/v1/posts/posts_by_category/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Tag slug is required
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
Bad Request: /cms-api/v1/posts/posts_by_category/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
Watching for file changes with StatReloader
Not Found: /
Not Found: /favicon.ico
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
C:\Users\admin\Desktop\realtech-blogx\backend\cms\cms\views.py changed, reloading.
Watching for file changes with StatReloader
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Tag slug is required
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
Bad Request: /cms-api/v1/posts/posts_by_category/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Tag slug is required
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
Bad Request: /cms-api/v1/posts/posts_by_category/
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Tag slug is required
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
Bad Request: /cms-api/v1/posts/posts_by_category/
Watching for file changes with StatReloader
Category slug is required
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Bad Request: /cms-api/v1/posts/posts_by_tag/
Category slug is required
Bad Request: /cms-api/v1/posts/posts_by_category/
Tag slug is required
Bad Request: /cms-api/v1/posts/posts_by_tag/
Internal Server Error: /auth/token/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in default
    return tuple(item for item in obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rest_framework\utils\encoders.py", line 66, in <genexpr>
    return tuple(item for item in obj)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 78, in __iter__
    for chunk in self.chunks():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\base.py", line 55, in chunks
    self.seek(0)
    ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\utils.py", line 45, in <lambda>
    seek = property(lambda self: self.file.seek)
                                 ^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 49, in _get_file
    self._require_file()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 44, in _require_file
    raise ValueError(
ValueError: The 'profile_picture' attribute has no file associated with it.
Watching for file changes with StatReloader
